spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
org:
  planqk:
    gateway:
      nisq:
        analyzer:
          uri: http://localhost:5010

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.planqk.gateway: DEBUG
