name: Gateway CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:

  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
